slug: vinetracker
name: VineTracker
version: 1.5.3
url: https://github.com/decompil3d/homeassistant-addon-vinetracker
stage: experimental
description:
  Add a HomeAssistant panel to track Vine order ETVs
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: decompil3d/image-{arch}-homeassistant-addon-vinetracker
homeassistant_api: true
host_network: true
ingress: true
init: false
panel_title: Vine
panel_icon: fa-brands:amazon
panel_admin: false
map:
  - type: share
    read_only: False
